"use strict";

let CONSTANTS = {};

CONSTANTS.SERVER = {
  ONE: 1,
};

CONSTANTS.AVAILABLE_AUTHS = {
  ADMIN: 1,
  USER: 2,
};

CONSTANTS.USER_TYPES = {
  ADMIN: 1,
  USER: 2,
};

CONSTANTS.USER_STATUS = {
  ACTIVE: "active",
  BLOCKED: "blocked",
};

CONSTANTS.SERVICE_TYPE = {
  WASTE_COLLECTION: "WASTE_COLLECTION",
};
CONSTANTS.PASSWORD_PATTER_REGEX =
  /^(?=.{6,})(?=.*[a-z])(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$/;

CONSTANTS.OTP_EXPIRY_DURATION = 5;

CONSTANTS.MESSAGES = require("./messages");

CONSTANTS.SECURITY = {
  JWT_SIGN_KEY: "fasdkfjklandfkdsfjladsfodfafjalfadsfkads",
  BCRYPT_SALT: 8,
  STATIC_TOKEN_FOR_AUTHORIZATION: "58dde3df315587b279edc3f5eeb98145",
};

CONSTANTS.ERROR_TYPES = {
  DATA_NOT_FOUND: "DATA_NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  FORBIDDEN: "FORBIDDEN",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  SOCKET_ERROR: "SOCKET_ERROR",
  INVALID_MOVE: "invalidMove",
};

CONSTANTS.GENDER_TYPES = {
  MALE: 1,
  FEMALE: 2,
};

CONSTANTS.TOKEN_TYPES = {
  LOGIN: 1,
  RESET_PASSWORD: 2,
  OTP: 3,
};

CONSTANTS.AVAILABLE_EXTENSIONS_FOR_FILE_UPLOADS = ["png", "jpg", "jpeg"];

CONSTANTS.PAGINATION = {
  DEFAULT_LIMIT: 50,
  DEFAULT_NUMBER_OF_DOCUMENTS_TO_SKIP: 0,
};

CONSTANTS.PROJECT_STATUS = {
  PENDING: "pending",
  IN_PROGRESS: "inprogress",
  COMPLETED: "completed",
};

CONSTANTS.PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_LIMIT: 10,
};

module.exports = CONSTANTS;
